### PR TITLE
Updated the workflow file.

### PR DESCRIPTION
**Pull request by DylanCheetah**
I have updated the workflow file so that it saves the "prebuilt" folder as a workflow artifact which can be downloaded via the page that lists the completed jobs.

### CODE REVIEW

**Comment by pmp-p** [comment]
great ! let's see if it's possible to get  ```/home/runner/work/pydk/pydk/*/apkroot-*/usr/include``` too

**Comment by pmp-p** [comment]
according to https://github.com/marketplace/actions/upload-a-build-artifact link you sent me it should be possible to use relative paths for the directory so maybe just "prebuilt" , "wasm/apkroot-wasm/usr/include" and "aosp/apkroot-*/usr/include"

**Review by pmp-p — COMMENTED** [review]
prebuilt folder is whole moving it is ok
but ```mv */apkroot-*/usr/include staging``` won't work, to preserve folder struct  maybe use command "tar" instead of moving

**Review by pmp-p — APPROVED** [review]
That looks good enough for a test ride.
Improvements can come later, first thing probably would be to have a common include folder deduplicating all arch + one per arch.

**Comment by DylanCheetah** [comment]
I just tried it out and the "mv" command doesn't retain the full path of the folders. Therefore, I have switched to using "tar" to create a gzipped tarball which is then stored as a workflow artifact. This will result in a zip file containing the gzipped tarball, but it should work properly this time. I'm currently running another test build.

**Comment by pmp-p** [comment]
it seems hard to tweak things in the worlflow file, maybe just  consider  "prebuilt" folder to move inside "staging" to be zipped
and then i'll later build a "sdkroot" folder with same structure as prebuilt for includes but from main script

also it's not a "release" it's really just a handfull of prebuilt for doing simple app in pure python because for complex things you need host interrogate for building C++ modules or target pip for rebuilding cpython modules.

**Comment by DylanCheetah** [comment]
It succeeded this time. I got a zip file containing a gzipped tarball with the following structure:

```
aosp/
    apkroot-arm64-v8a/
    apkroot-armeabi-v7a/
    apkroot-x86/
    apkroot-x86_64/
prebuilt/
    arm64-v8a/
    armeabi-v7a/
    wasm/
    x86/
    x86_64/
wasm/
    apkroot-wasm/
```

Where each respective folder contains the files from the build. I can change the name of the artifact to something more like "pydk-prebuild.zip" if that would be more suitable.

**Comment by pmp-p** [comment]
"pydk-min.zip" would sound ok to me because that's what it is.

Then later "pydk-full.zip" can come for  a chroot or a jslinux deployment with all the building tools.

Please do the change and i'll merge :)

**Comment by pmp-p** [comment]
Thanks for the contribution !

**Comment by DylanCheetah** [comment]
np

**Pull request merged**
